---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1fdh9agpecvy0lf3ysklx08nrczuldyymacclv463rm88xpapx3zqmju5gx
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1fdh9agpecvy0lf3ysklx08nrczuldyymacclv463rm88xpapx3zqmju5gx
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1fdh9agpecvy0lf3ysklx08nrczuldyymacclv463rm88xpapx3zqmju5gx
