kind: ENC[AES256_GCM,data:EzgTfqfl,iv:O5m2RmIMSwnmLR1EwD1Ez4M4JYHTNQP+4JznQgvTehE=,tag:zNYxXG2yzS5LBb+QNoA4uA==,type:str]
ansible_user: ENC[AES256_GCM,data:5GMbuUoO,iv:Q4wX20kTG5FrDNQ4vkOWfNUTiwEf2Cf1B5jNgvJCfEs=,tag:OawGcYYFdMt54a6TDIaBOA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:71LPymkkvR36dhc=,iv:Y0Gx3sdg190hS53y6F8sS5cyGjE71wAFJo2PRetSnIw=,tag:UarqQ2nsAx1LRMWCm+Vdsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd2UxSjh3ZC9XR2tGbTc2
            SWgxbjdGcUMwZDZKU0xUYTBoejVQZlRTTURFCkdXNE1KWlZrK0dSeTRUMFBkM0Fl
            b0d3SGoxb1A0ZWhVMlh4U0loM2JvVzgKLS0tIEFaeFdjS0FSaEhFZitYbUdqM01l
            T21qZ2U4N09rUm81aTAyV0VNZ1VCWVkK+zRwRQHeud9wLM8LL3SSwhCoIYWU+NaK
            WRnUguxgRtQ8D4DhHvXPFzJnQP6i4gx/eOfL1FgMxmA6Yc8M6NLq2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-15T03:18:50Z"
    mac: ENC[AES256_GCM,data:qq8GWWCl0v6Vh1ReIo56kL4NWXU+VdteURW4YhPVAMIxAa8lCaWtxmN2bCmJH6AhKIER2yTv8d67X2ILA1Rq2dGGfB1VbWRrr4ukE+rs2+4Ly6IS03ymtuf2/JQEEZSkSr0fyclifE0MjRT4bf0bPv71eGLi0U+vd969v8Yuekc=,iv:hmWcPThD+5QnO1kf9Vb/ofrdgsqAIr+UtmbpF772WPA=,tag:KrISWobv1Mfz8SIJRfPVdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
