apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:o3kL+hfPAwK7HqXNP14XQcsik9Hzsz9Y+Zlf5qQHuzuRg8yV6w==,iv:x1vJMJZWy1D1gVa9gATBFF4O+b0H9oxinswi26RdUTA=,tag:SqASXKoalHXD+VCwGCayCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWW53YytUSE5ETFlCVWFT
            Z0ZuRUFXTytsS2FDMlllUXJvZ016V3lib3k4CmJxMStZanlMK08vRlhFelJGYTBG
            UzFpbzBTRkNTQWRqczdGVWRNS1cwVXcKLS0tIHpoZnRvaWlGMy9TOFBMUXJ2dDFn
            NkhhTmhPRDVoSUpDTUtDOWg4cGs2Y0kK8ApTblHFCiMF/totmSypiApmf7ZNKYEw
            m9PAlp6PyqTqkBozo9CtZdLtFmJ0g0V/tO7Khh8IvNlmLN7Y4Fj49w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-15T04:41:31Z"
    mac: ENC[AES256_GCM,data:6T7SXEcDrCHDYk7ZFtdBt4NdMoJEOtBkH3Q0pPVPc71irBaNz0PgumRa/7WdoSb6Rulz9BldAFV/6TgsmhLey2y6Gb5OP2BiS4UDfCvBZ2mmoM7jyvW21ZC48M8viiOlUFkeDOLb31tttvAaQNWAKaUdeXRAyex7Ln3oShy3l90=,iv:rbMksGxUNw8TvNU3+DeUvDL9HksI1TYjtHemsvLUw88=,tag:yHpPD7lSVjN6ZaXqxTVXag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
