apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:SIPQz93ThHa6yQa1tiqmcwxOTKusEDIbQhaK/hu25c2c37zT0iUmviIGMDUIvmzmFNteMbi4bQoHCsVd,iv:abzB4iJoNafB++OMCmmIfBzB10ubAE3G579/dgWieBc=,tag:L8LLw/GZVOXu7HhMczdcRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaUVZRkNhQjhrYU96aVJz
            VDM4aC85K3ltY24rMFJiSzRVRDdKN2RsYlVZCkUxTjJCTFlPRGdTY1Eyd0JPSWVK
            bzJyL1FXa3pmK2JMUWtMRUtoVDR3SlEKLS0tIFZSSnNDOTY3RVRwQ1ZXMDh1ZHlj
            T2ZpWE5wUWdwVThocEt4dEpzYWxhRWcK0go6EpPgw52bhIPG4ItG2KMFn9U/vq7k
            n+1BwfU5FF8AllQn1CsMK0AWbmeYj1WuqbIWw7mdzAc6DtsGrKuBzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-15T03:18:50Z"
    mac: ENC[AES256_GCM,data:3l6OndXvxswPl83I9lTkis0mgpf5v/uzqeJ+1nLc/ker2r1kl19qEnZdCOlyy4ufmn/tnX0TqmaC54RPJ5zpIHlE9QXOfdHPHbeoYV90f0Pf3mbRIaKRlfqQAp8cEFofja4fk2cezkR6CzxYD25sZDCl4bXMmzBUKnXVh8TIdtY=,iv:CsCqbk5RozhAe0g9rWdZnN4Ifyem2B8nBhlaljkXkcA=,tag:bD87AJGt9rl9ABQ/BGaMYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
