apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:xYTJFU2THiGPjsplaDAhPWxM8/s9ITKrWQZOZCjBfEUYohrXrQ==,iv:p/2A2nxSsxB1QVp0h2NUC5Fkd/huil1UMbK4xSILScs=,tag:8uva9G/R9mAjFTymzfmRAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc0ZSVU4rVUpkeHlweGVL
            bzJxTFN0dnBuTGtwbFNwVVF5UHJld1dVUmcwCjJJTGlyeWJ1YXNweHJ6dVdXT2lj
            SEdTcVhMcjcrNEZJZW04dUJmSXNFbGcKLS0tIHQwUUdZVTdlK01Mblo1ZlA2QmtF
            bkFQNEY5aE82TVJoc1NRRWVFOVMzeGMKB4frz03ax9gpb54kVTCgDS/oO5uaH6zq
            z/WKKke/kFKDPMLZAvgQuBmkWtCCx/3EYEeQdYF79CawOCDlzGDXMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-15T03:18:50Z"
    mac: ENC[AES256_GCM,data:4WqnIBmAl6qYi8PqI2lFJAlQW1fyZe5Zgnmfkpo1shd/QYjVi7EpkrgXjCx2bXxFsYeiJENk68VWhOemK2mGXXp9KDy8jqp7EUOXJmocwvb8/X7q0igcxkkQnuiPuoH9oBSkV+PcxmtZP7xS1LLkBxTxCxQcShkhYpjr5oWQ8UU=,iv:AgB4tW/5qCGdyXlD5v6wXiF3r8YAyEbJIwGflrEkgso=,tag:cDw9X53QUYEp2Q/t0bHi+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
