apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kBrRf/LVHCeqAA==,iv:CLZUlUyxasBPMx+zjR9d+j2d1lGgo0zXDPhnzi7iAlQ=,tag:HOBpgQh+NsDkOQPoKVqzkQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uBs6oUwgqbrewrdbB+ojFlrHVn+K/98onViy0f4CZQ==,iv:R384wi3P6PRSfKXKS5KonfMlgDDrlqAsemokT850Feg=,tag:kFywrFYEKQ1INDZgNfPFmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fdh9agpecvy0lf3ysklx08nrczuldyymacclv463rm88xpapx3zqmju5gx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZVhRZGMzUFNsemVSUnM1
            WGttTnBWd0ZzV2xibUJTbCtiYmFuZTdYZWdNClBmVnV1c2xuelRGRWZHTjJZVTcy
            Nm5TK09vWGZOWjBZRkFZU0tHVWptZVUKLS0tIGRXMUNlQWVyM2tnQm9kU3NkSVZS
            SEtYaWdlNkRwVVNPcm1LZ01sdGU2YTAK2pllZWOBkoPDfQj6y/iGDbBjhunmsnDg
            1m1QV+Tp9uqR6cjjme1Iu/JgDYxJxRhrn9Re6hFZESxT3ISvBj1b9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T22:53:44Z"
    mac: ENC[AES256_GCM,data:2MHn7BOP7kdGO0He74abCWjGWSVenvo8Lk+Un6kXmC/VdKiMsFikfVaHqBTe/CxJ/QToal7xh+Y8aEBE16TIbKCMBxeo8BvzjTPKiBJ8LNHCU8TEaDFccDLsLJSmHuyjlgu/e7t4+p3UNbU/eqy4Hx/IWsYwipsctrh8zqpyQEg=,iv:k/CkeE4uNQ0OnRnvgR1RePNtVEv/b0JSdw8fQ2tNl14=,tag:ufhvoEWGn1AlkZ8BQi8GoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
