---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "172.20.30.175"
  METALLB_LB_RANGE: "172.20.30.150-172.20.30.174"
  METALLB_K8S_GATEWAY_ADDR: "172.20.30.174"
  METALLB_INGRESS_ADDR: "172.20.30.173"
