---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflare-ddns/ks.yaml
  - ./external-dns/ks.yaml
  - ./traefik/
  - ./k8s-gateway/ks.yaml
  - ./error-pages/
  #- ./authelia/
