---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-backups-secrets
  namespace: longhorn-system
stringData:
    AWS_ENDPOINTS: "${BOOTSTRAP_AWS_ENDPOINT}"
    AWS_ACCESS_KEY_ID: "${BOOTSTRAP_AWS_ACCESSKEY}"
    AWS_SECRET_ACCESS_KEY: "${BOOTSTRAP_AWS_SECRETKEY}"
